### PR TITLE
adding pdx chapter to index.html

### PR DESCRIPTION
**Pull request by taylor-l-beach**

### CODE REVIEW

**Comment by andyshora** [comment]
@taylor-l-beach you need to fork this repo and make your changes mate. This pull request should just be an additional link to your chapter at the top :-)

**Comment by taylor-l-beach** [comment]
Ya sorry, Tomas's bad... We've got everything set up now:

http://taylor-l-beach.github.io/beerclub/

**Comment by taylor-l-beach** [comment]
@andyshora - ready for a merge now, I think everything is set up.  Hopefully PDX will have some posts up before the coming weekend!!

**Comment by andyshora** [comment]
@taylor-l-beach awesome man, can't wait to see the first pic! Btw, the 'no smiling' rule is optional :-)

**Pull request closed without merging**
